git-issue-mvp| function git_issue_track
show tracking remote when no argument.
--unset to unset tracking remote.

diff --git a/git-issue-mvp b/git-issue-mvp
--- a/git-issue-mvp
+++ b/git-issue-mvp
@@ -535,19 +535,59 @@ resolve_issue_remote() {
 
 
 git_issue_track() {
-  [ $# -eq 1 ] || { echo "usage: git issue track <remote>"; return 1; }
-  local remote=$1
-
-  # check remote exists
-  if ! git ls-remote --exit-code "$remote" >/dev/null 2>&1; then
-    echo "remote '$remote' not found"
+  #[ $# -eq 1 ] || { echo "usage: git issue track <remote>"; return 1; }
+  if [ "$#" -gt  1 ]; then
+    echo "usage: git issue track (<remote>|--unset)"
     return 1
   fi
 
-  git config issue.remote "$remote" \
-    || { echo "failed to set issue.remote"; return 1; }
+  if [ "$#" -lt 1 ]; then
+    #echo "usage: git issue track <remote>"
 
-  echo "Issues now track remote '$remote'"
+    # from function resolve_issue_remote
+    local r
+    r=$(git config --get issue.remote)
+    [ -n "$r" ] && { echo "Currently tracking $r"; return; }
+    
+    echo "Tracking remote is not set."
+
+        # 3. remote.pushDefault
+    r=$(git config --get remote.pushDefault)
+    [ -n "$r" ] && { echo "- remote.pushDefault set to $r"; return; }
+
+    # 4. branch upstream (only if on branch)
+    local branch
+    branch=$(git symbolic-ref --quiet --short HEAD 2>/dev/null)
+    if [ -n "$branch" ]; then
+      r=$(git config --get branch.$branch.remote)
+      [ -n "$r" ] && { echo "- branch.CURRENT_BRANCH($branch).remote set to $r"; return; }
+    fi
+
+    # 5. fallback
+    echo "- remote would be origin if not specified"
+
+    return 1
+  fi
+  
+  if [ "$#" -eq 1 ]; then
+    local remote=$1
+
+    if [ "$remote" = "--unset" ]; then
+      git config --unset issue.remote \
+      || { echo "failed to unset issue.remote"; return 1; }
+    fi
+
+    # check remote exists
+    if ! git ls-remote --exit-code "$remote" >/dev/null 2>&1; then
+      echo "remote '$remote' not found"
+      return 1
+    fi
+
+    git config issue.remote "$remote" \
+      || { echo "failed to set issue.remote"; return 1; }
+
+    echo "Issues now track remote '$remote'"
+  fi
 }
 
 
